class AppConstants {
  static List<String> allowedHosts = [
    'www.bankofbaroda.in',
    'www.bankofindia.co.in',
    'bankofmaharashtra.in',
    'canarabank.com',
    'www.centralbankofindia.co.in',
    'www.indianbank.in',
    'www.iob.in',
    'punjabandsindbank.co.in',
    'www.pnbindia.in',
    'www.pnbindia.in',
    'bank.sbi',
    'www.ucobank.com',
    'www.unionbankofindia.co.in',
    'www.axisbank.com',
    'www.bandhanbank.com',
    'www.csb.co.in',
    'www.dcbbank.com',
    'www.dhanbank.com',
    'federalbank.co.in',
    'www.hdfcbank.com',
    'www.icicibank.com',
    'www.idbibank.in',
    'www.idfcfirstbank.com',
    'www.indusind.com',
    'www.jkbank.net',
    'karnatakabank.com',
    'www.kvb.co.in',
    'www.kotak.com',
    'www.nainitalbank.co.in',
    'www.rblbank.com',
    'southindianbank.com',
    'www.tmb.in',
    'www.yesbank.in',
  ];

  static bool validateUrl = true;
}
